version: '3.8'

services:
  comfyui:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: comfyUI
    runtime: nvidia
    entrypoint: ["/opt/nvidia/nvidia_entrypoint.sh"]
    privileged: true
    environment:
      - CUDA_VISIBLE_DEVICES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - KUBECONFIG=/home/devuser/.kube/config
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube:/home/devuser/.kube:cached
      - ${HOME}/git/comfyUI:/workspace:cached
      - ${HOME}/.cursor/mcp.json:/home/devuser/.cursor/mcp.json:cached
      - /mnt/ai-models:/mnt/ai-models:cached
    command: sleep infinity
    user: devuser
    working_dir: /workspace
